# Generated by Django 5.1.6 on 2025-02-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
